name: WispBlockLookGet
version: ${project.version}
main: dev.yhdiamond.wispblocklookget.WispBlockLookGet
api-version: 1.16
commands:
  blocklookget:
    usage: /blocklookget <start/stop>
    description: Starts the Wisp Block-Look-Get challenge
